leads/urls.py
from django.urls import path
from leads.views import lead_list, lead_detail, lead_create, lead_update, lead_delete

app_name = "leads"

urlpatterns = [
    path('', lead_list, name="lead-list"),
    path('<int:pk>/', lead_detail, name="lead-detail"),
    path('create/', lead_create, name="lead-create"),
    path('update/<int:pk>', lead_update, name="lead-update"),
    path('delete/<int:pk>', lead_delete, name="lead-delete")
]

mysite/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('setup.urls', namespace="setup")),
    path('leads/', include('leads.urls', namespace="leads"))
]

# if settings.DEBUG:
#     urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

setup/urls.py
from django.urls import path
from setup.views import home
from django.contrib.auth.views import LoginView, LogoutView
from setup.views import SignupView

app_name = "setup"

urlpatterns = [
    path('', home, name="home-page"),
    path('login/', LoginView.as_view(), name="login"),
    path('logout/', LogoutView.as_view(next_page='/'), name="logout"),
    path('signup/', SignupView.as_view(), name="signup"),

]

leads/models.py
from django.db import models
from setup.models import User

class Lead(models.Model):
    first_name = models.CharField(max_length=20)
    last_name = models.CharField(max_length=20)
    age = models.IntegerField(default=0)
    agent = models.ForeignKey("Agent", on_delete=models.CASCADE)

    def __str__(self) -> str:
        return f"{self.first_name} {self.last_name}"

class Agent(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    first_name = models.CharField(max_length=20)
    last_name = models.CharField(max_length=20)

    def __str__(self) -> str:
        return f"{self.first_name} {self.last_name}"

setup/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

class User(AbstractUser):
    pass


class Company(models.Model):
    company_name = models.CharField(max_length=30)
    since_year = models.IntegerField()
    slogan = models.CharField(max_length=60)
    vision = models.TextField(max_length=400)

    def __str__(self):
        return self.company_name

leads/forms.py
from django import forms
from .models import Lead

class LeadModelForm(forms.ModelForm):
    class Meta:
        model = Lead
        fields = (
            'first_name',
            'last_name',
            'age',
            'agent',
        )

class LeadForm(forms.Form):
    first_name = forms.CharField()
    last_name = forms.CharField()
    age = forms.IntegerField(min_value=0,)

setup/forms.py
from django import forms
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm

User = get_user_model()

class SetupUserCreationForm(UserCreationForm):
    class Meta(UserCreationForm.Meta):
        model = User
        fields = ("username", "email")  # Add any other fields if needed

leads/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from leads.models import Lead, Agent
from leads.forms import LeadForm, LeadModelForm


def lead_list(request):
    leads = Lead.objects.all()
    context = {
        "leads": leads
    }
    return render(request, 'leads/lead_list.html', context)


def lead_detail(request, pk: int):
    lead = Lead.objects.get(id=pk)
    context = {
        "lead": lead
    }
    return render(request, 'leads/lead_detail.html', context)


def lead_create(request):
    form = LeadModelForm()
    if request.method == "POST":
        form = LeadModelForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect(f"/leads/")
    context = {
        "form": form
    }
    return render(request, 'leads/lead_create.html', context)

def lead_update(request, pk: int):
    lead = Lead.objects.get(id=pk)
    form = LeadModelForm(instance=lead)
    if request.method == "POST":
        form = LeadModelForm(request.POST, instance=lead)
        if form.is_valid():
            form.save()
            return redirect("/leads/")
    context = {
        "lead": lead,
        "form": form
    }
    return render(request, "leads/lead_update.html", context)

def lead_delete(request, pk: int):
    lead = Lead.objects.get(id=pk)
    lead.delete()
    return redirect("/leads/")

setup/views.py
from django.shortcuts import render
from setup.models import Company
from django.views import generic
from django.urls import reverse
from setup.forms import SetupUserCreationForm

def home(request):
    company = Company.objects.get(company_name="Fashion 360")
    context = {
        "company": company
    }
    return render(request, 'setup/home.html', context)


class SignupView(generic.CreateView):
    template_name = "registration/signup.html"
    form_class = SetupUserCreationForm

    def get_success_url(self) -> str:
        return reverse("setup:login")

leads/templates/leads/index.html
<!DOCTYPE html>
<html>
<head>
    <meta charset='utf-8'>
    <meta http-equiv='X-UA-Compatible' content='IE=edge'>
    <title>Home</title>
    <meta name='viewport' content='width=device-width, initial-scale=1'>
    <link rel='stylesheet' type='text/css' media='screen' href='main.css'>
    <script src='main.js'></script>
    <style>
        body, html {
            height: 100%;
            margin: 0;
            display: flex;
            justify-content: center; /* Center horizontally */
            align-items: center;   /* Center vertically */
        }

        .centered-div {
            width: 300px;
            height: 200px;
            background-color: #f2f2f2;
            border: 2px solid #ccc;
            text-align: center;
            line-height: 200px; /* Center text vertically within the div */
            font-size: 20px;
        }
        .hello-world {
            background-color: black;
            color: white;
        }
    </style>
</head>
<body>
    <div class="hello-world">
        <h1>{{company}}</h1>
        <h3>Since {{since}}</h3>
        <p>Vision<br>{{vision}}</p>
        <li>
        {% for ld in leads %}
            <ul>Last Name: {{ld.last_name}}, Agent: {{ld.agent}}</ul>
        {% endfor %}
        </li>
    </div>
</body>
</html>

leads/templates/leads/lead_create.html
{% extends 'base.html' %}
{% block content %}
    <div class="row">
        <div class="header-section col-12">
            <div><a href="{% url 'leads:lead-list' %}">Go back to Leads</a></div>
            <div><h1>Create a new Lead</h1></div>
        </div>
        <div class="form-section col-12">
            <form method="POST">
                {% csrf_token %}
                {{form.as_p}}
                <button type="submit">Submit</button>
            </form>
        </div>
    </div>
{% endblock content %}

leads/templates/leads/lead_detail.html
{% extends 'base.html' %}
{% block content %}
    <div>
        <a href="{% url 'leads:lead-list' %}">Go back to Leads</a>
        <p>Lead From: {{lead.first_name}} {{lead.last_name}}, {{lead.age}} years old</p>
        <p>Agent Responsible for this lead: {{lead.agent}}</p>
    </div>
{% endblock content %}

leads/templates/leads/lead_list.html
{% extends 'base.html' %}
{% block content %}
    <div class="leads-section">
        <div class="row">
            <div class="col-12">
                <a href="{% url 'leads:lead-create' %}">Create New Lead</a>
            <h1>Got Leads</h1>
        </div>
        <div class="col-12">
            <ul>
                {% for ld in leads %}
                <li><a href="{% url 'leads:lead-detail' ld.pk%}">{{ld.last_name}}</a>
                    &nbsp;&nbsp;&nbsp;
                    <a href="{% url 'leads:lead-update' ld.pk %}">Update</a>
                    &nbsp;&nbsp;&nbsp;
                    <a href="{% url 'leads:lead-delete' ld.pk %}" style="background-color: red;">Delete</a>
                </li>
                {% endfor %}
            </ul>
        </div>
    </div>
    </div>
{% endblock content %}

leads/templates/leads/lead_update.html
{% extends 'base.html' %}
{% block content %}
    <div class="header-section">
        <div><a href="{% url 'leads:lead-list' %}">Go back to Leads</a></div>
        <div><h1>Update Lead: {{lead.last_name}}</h1></div>
    </div>
    <div class="form-section">
        <form method="POST">
            {% csrf_token %}
            {{form.as_p}}
            <button type="submit">Submit</button>
        </form>
    </div>
{% endblock content %}

leads/templates/leads/leads_detail.html
<!DOCTYPE html>
<html>
<head>
    <meta charset='utf-8'>
    <meta http-equiv='X-UA-Compatible' content='IE=edge'>
    <title>{{lead}}</title>
    <meta name='viewport' content='width=device-width, initial-scale=1'>
    <link rel='stylesheet' type='text/css' media='screen' href='main.css'>
    <script src='main.js'></script>
</head>
<body>
    <div>
        {{lead.first_name}} {{lead.last_name}}
    </div>
</body>
</html>

leads/templates/leads/leads_list.html
<!DOCTYPE html>
<html>
<head>
    <meta charset='utf-8'>
    <meta http-equiv='X-UA-Compatible' content='IE=edge'>
    <title>Home</title>
    <meta name='viewport' content='width=device-width, initial-scale=1'>
    <link rel='stylesheet' type='text/css' media='screen' href='main.css'>
    <script src='main.js'></script>
    <style>
        body, html {
            height: 100%;
            margin: 0;
            display: flex;
            justify-content: center; /* Center horizontally */
            align-items: center;   /* Center vertically */
        }

        .centered-div {
            width: 300px;
            height: 200px;
            background-color: #f2f2f2;
            border: 2px solid #ccc;
            text-align: center;
            line-height: 200px; /* Center text vertically within the div */
            font-size: 20px;
        }
        .leads-section {
            background-color: black;
            color: white;
            padding: 50px;
        }
    </style>
</head>
<body>
    <div class="leads-section">
        <h1>Got Leads</h1>
        <ul>
        {% for ld in leads %}
            <li><a href="/leads/{{ld.id}}">{{ld.last_name}}</a></li>
        {% endfor %}
        </ul>
    </div>
</body>
</html>

setup/templates/setup/home.html
{% extends 'base.html' %}
{% block content %}
    <div class="company-info">
        <h1>{{company.company_name}}</h1>
        <h4>{{company.since}}</h4>
        <h4>{{company.slogan}}</h4>
        <p>{{company.vision}}</p>
    </div>
{% endblock content %}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>My CRM</title>
    <link href="{% static 'css/styles.css' %}" rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
    <script src="{% static 'js/main.js' %}"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+jjXkk+Q2h455rYXK/7HAuoJl+0I4" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.6/dist/umd/popper.min.js" integrity="sha384-oBqDVmMz9ATKxIep9tiCxS/Z9fNfEXiDAYTujMAeBAsjFuCZSmKbSSUnQlmh/jp3" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.min.js" integrity="sha384-cuYeSxntonz0PPNlHhBs68uyIAVpIIOZZ5JqeqvYYIcEL727kskC66kF92t6Xl2V" crossorigin="anonymous"></script>
</head>
<body>
    <div class="row">
        <div class="col-12 navbar-section">
            {% include 'navbar.html' %}
        </div>
        <div class="col-12 content-section">
            {% block content %}
                <!-- Content block here -->
            {% endblock content%}
        </div>
        <div class="col-12 footer-section">
            {% include 'footer.html' %}
        </div>
    </div>
</body>
</html>

templates/footer.html
<div>
    <pre>Powered by Shah Spider</pre>
</div>

templates/navbar.html
    <nav class="navbar navbar-expand-lg bg-light">
        <div class="container-fluid">
            <div>
                <a class="navbar-brand" href="{% url 'setup:home-page' %}">Fashion 360</a>
            </div>
            <div class="row">
                <div class="col col-8">
                    <form class="d-flex" role="search">
                        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
                        <button class="btn btn-outline-success" type="submit">Search</button>
                    </form>
                </div> 
                <div class="col col-4">
                    {% if not request.user.is_authenticated %}
                        <a class="" href="{% url 'setup:signup' %}">Sign Up</a>
                    {% endif %}

                    {% if request.user.is_authenticated %}
                        {{request.user.username}} &nbsp;
                        <a class="" href="{% url 'setup:logout' %}">Log out</a>
                    {% else %}
                    <button class="btn">
                        <a class="" href="{% url 'setup:login' %}">Login</a>
                    </button>
                    {% endif %}
                </div>
            </div>
        </div>
    </nav>